version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
    ports:
      - "9906:3306"
  web:
    image: php-mysql-basic
    container_name: php_web
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
