version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile

    image: laravel-docker
    ports: 
      - 8080:80
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
    ports:
      - "9906:3306"
